name: blogsphere
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  bloc: ^8.1.3
  cupertino_icons: ^1.0.2
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_dotenv: ^5.1.0
  fpdart: ^1.1.0
  gap: ^3.0.1
  get_it: ^7.6.7
  hive: ^4.0.0-dev.2
  image_picker: ^1.0.7
  internet_connection_checker_plus: ^2.2.0
  intl: ^0.18.0
  isar_flutter_libs: ^4.0.0-dev.14
  path_provider: ^2.1.2
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.3.4
  uuid: ^4.3.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
  fonts:
    - family: Mirador
      fonts:
        - asset: assets/fonts/Mirador-Bold.otf
          weight: 700
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
